projects:
  schdlr:
    schemaPath: src\graphql\schema.json
    includes:
      - src\graphql\**\*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        graphQLApiId: 6s4g44xq7vg7fnwtqz3kkffn3e
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src\graphql
        region: us-east-1
      endpoints:
        prod: >-
          https://7p57flfherd7fpejz37d653sv4.appsync-api.us-east-1.amazonaws.com/graphql
