// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:a533e830-2952-4198-8564-7bd1d0183f1b",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_xsnGipK3A",
    "aws_user_pools_web_client_id": "4j3egardp7r5ids9eqg6urc6gp",
    "oauth": {
        "domain": "schdlr-dev.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "schdlr://",
        "redirectSignOut": "schdlr://",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
