// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:e86a8c71-fcd4-406f-876a-537a9c10c96f",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_vssBv0ZMF",
    "aws_user_pools_web_client_id": "4gkotf3qfq1msb26tatk8upoea",
    "oauth": {
        "domain": "schdlr-dev.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "schdlr://",
        "redirectSignOut": "schdlr://",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_mobile_analytics_app_id": "9d52361b9e2b467abc8e65c42cf1b0b9",
    "aws_mobile_analytics_app_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://jknfmzbdcff5jkoux5z2kohqn4.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "schdlre4a77eacabcb468f9af1f2063df20dd7-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
