export default [
  { name: 'Normal', id: 'EVENT' },
  { name: 'Task', id: 'TASK' },
  { name: 'Reminder', id: 'REMINDER' },
  { name: 'Lecture', id: 'LECTURE' },
  { name: 'Test', id: 'TEST' },
  { name: 'Tutorial', id: 'TUTORIAL' },
  { name: 'Practical', id: 'PRACTICAL' },
  { name: 'Examination', id: 'EXAMINATION' },
  { name: 'Hobby', id: 'HOBBY' },
  { name: 'Study', id: 'STUDY' },
  { name: 'Work', id: 'WORK' },
  { name: 'Sport', id: 'SPORT' },
  { name: 'Meeting', id: 'MEETING' },
  { name: 'Fetival', id: 'FESTIVAL' },
  { name: 'Ceremony', id: 'CEREMONY' },
  { name: 'Competition', id: 'COMPETITION' },
  { name: 'Funfare', id: 'FUNFARE' },
  { name: 'Party', id: 'PARTY' },
  { name: 'Happening', id: 'HAPPENING' },
  { name: 'Interview', id: 'INTERVIEW' },
];