/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:b12fa795-1bfd-46ed-b0ba-3e95a7d25dc0",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_2yTgdTeoh",
    "aws_user_pools_web_client_id": "ftgvophskp6dik3r8vit19r41",
    "oauth": {
        "domain": "schdlr-prod.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "schdlr://",
        "redirectSignOut": "schdlr://",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_appsync_graphqlEndpoint": "https://adeesfck7fhmxjpl47t5oklbue.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "schdlrassets-prod",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "Bookmark-delta-prod",
            "region": "us-east-1"
        },
        {
            "tableName": "Comment-delta-prod",
            "region": "us-east-1"
        },
        {
            "tableName": "Event-delta-prod",
            "region": "us-east-1"
        },
        {
            "tableName": "Follow-delta-prod",
            "region": "us-east-1"
        },
        {
            "tableName": "Schedule-delta-prod",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
