// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:c12037b3-0522-4e81-b8d3-9b163b9a55d0",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_AxP4tm7Sj",
    "aws_user_pools_web_client_id": "3fa3ecqh8buqmv74im6ff9le7d",
    "oauth": {},
    "federationTarget": "COGNITO_IDENTITY_POOLS"
};


export default awsmobile;
