// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:0111554c-647f-4a8f-9da2-71d13accc10d",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_mkzoRykDC",
    "aws_user_pools_web_client_id": "3k3taa08k0340v7isgu523dnl7",
    "oauth": {},
    "federationTarget": "COGNITO_IDENTITY_POOLS",
    "aws_appsync_graphqlEndpoint": "https://g5zu7uosu5gfherxf2ckl3clbi.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_mobile_analytics_app_id": "51618c5554624f51be8f7f5c94131a6c",
    "aws_mobile_analytics_app_region": "us-east-1"
};


export default awsmobile;
