/* eslint-disable */
// this is an auto generated file. This will be overwritten

export const createSchedule = `mutation CreateSchedule($input: CreateScheduleInput!) {
  createSchedule(input: $input) {
    id
    name
    description
    status
    isPublic
    isFollowing
    isAuthor
    author {
      id
      name
      email
      pictureUrl
      followingCount
      createdCount
      createdSchedules {
        id
        name
        description
        status
        isPublic
        isFollowing
        isAuthor
        eventsCount
        followersCount
        createdAt
        updatedAt
      }
      followingSchedules {
        id
        name
        description
        status
        isPublic
        isFollowing
        isAuthor
        eventsCount
        followersCount
        createdAt
        updatedAt
      }
    }
    eventsCount
    followersCount
    followers {
      id
      name
      email
      pictureUrl
      followingCount
      createdCount
      createdSchedules {
        id
        name
        description
        status
        isPublic
        isFollowing
        isAuthor
        eventsCount
        followersCount
        createdAt
        updatedAt
      }
      followingSchedules {
        id
        name
        description
        status
        isPublic
        isFollowing
        isAuthor
        eventsCount
        followersCount
        createdAt
        updatedAt
      }
    }
    events {
      id
      title
      description
      venue
      startAt
      endAt
      allDay
      isCancelled
      repeat
      until
      forever
      eventType
      schedule {
        id
        name
        description
        status
        isPublic
        isFollowing
        isAuthor
        eventsCount
        followersCount
        createdAt
        updatedAt
      }
      isPublic
      cancelledDates
      bookmarksCount
      isBookmarked
      isAuthor
      author {
        id
        name
        email
        pictureUrl
        followingCount
        createdCount
      }
      commentsCount
      comments {
        id
        content
        isReply
        isAuthor
        createdAt
        updatedAt
      }
      createdAt
      updatedAt
    }
    createdAt
    updatedAt
  }
}
`;
export const updateSchedule = `mutation UpdateSchedule($input: UpdateScheduleInput!) {
  updateSchedule(input: $input) {
    id
    name
    description
    status
    isPublic
    isFollowing
    isAuthor
    author {
      id
      name
      email
      pictureUrl
      followingCount
      createdCount
      createdSchedules {
        id
        name
        description
        status
        isPublic
        isFollowing
        isAuthor
        eventsCount
        followersCount
        createdAt
        updatedAt
      }
      followingSchedules {
        id
        name
        description
        status
        isPublic
        isFollowing
        isAuthor
        eventsCount
        followersCount
        createdAt
        updatedAt
      }
    }
    eventsCount
    followersCount
    followers {
      id
      name
      email
      pictureUrl
      followingCount
      createdCount
      createdSchedules {
        id
        name
        description
        status
        isPublic
        isFollowing
        isAuthor
        eventsCount
        followersCount
        createdAt
        updatedAt
      }
      followingSchedules {
        id
        name
        description
        status
        isPublic
        isFollowing
        isAuthor
        eventsCount
        followersCount
        createdAt
        updatedAt
      }
    }
    events {
      id
      title
      description
      venue
      startAt
      endAt
      allDay
      isCancelled
      repeat
      until
      forever
      eventType
      schedule {
        id
        name
        description
        status
        isPublic
        isFollowing
        isAuthor
        eventsCount
        followersCount
        createdAt
        updatedAt
      }
      isPublic
      cancelledDates
      bookmarksCount
      isBookmarked
      isAuthor
      author {
        id
        name
        email
        pictureUrl
        followingCount
        createdCount
      }
      commentsCount
      comments {
        id
        content
        isReply
        isAuthor
        createdAt
        updatedAt
      }
      createdAt
      updatedAt
    }
    createdAt
    updatedAt
  }
}
`;
export const deleteSchedule = `mutation DeleteSchedule($input: DeleteScheduleInput!) {
  deleteSchedule(input: $input) {
    id
    name
    description
    status
    isPublic
    isFollowing
    isAuthor
    author {
      id
      name
      email
      pictureUrl
      followingCount
      createdCount
      createdSchedules {
        id
        name
        description
        status
        isPublic
        isFollowing
        isAuthor
        eventsCount
        followersCount
        createdAt
        updatedAt
      }
      followingSchedules {
        id
        name
        description
        status
        isPublic
        isFollowing
        isAuthor
        eventsCount
        followersCount
        createdAt
        updatedAt
      }
    }
    eventsCount
    followersCount
    followers {
      id
      name
      email
      pictureUrl
      followingCount
      createdCount
      createdSchedules {
        id
        name
        description
        status
        isPublic
        isFollowing
        isAuthor
        eventsCount
        followersCount
        createdAt
        updatedAt
      }
      followingSchedules {
        id
        name
        description
        status
        isPublic
        isFollowing
        isAuthor
        eventsCount
        followersCount
        createdAt
        updatedAt
      }
    }
    events {
      id
      title
      description
      venue
      startAt
      endAt
      allDay
      isCancelled
      repeat
      until
      forever
      eventType
      schedule {
        id
        name
        description
        status
        isPublic
        isFollowing
        isAuthor
        eventsCount
        followersCount
        createdAt
        updatedAt
      }
      isPublic
      cancelledDates
      bookmarksCount
      isBookmarked
      isAuthor
      author {
        id
        name
        email
        pictureUrl
        followingCount
        createdCount
      }
      commentsCount
      comments {
        id
        content
        isReply
        isAuthor
        createdAt
        updatedAt
      }
      createdAt
      updatedAt
    }
    createdAt
    updatedAt
  }
}
`;
export const createComment = `mutation CreateComment($input: CreateCommentInput!) {
  createComment(input: $input) {
    id
    content
    isReply
    toComment {
      id
      content
      isReply
      toComment {
        id
        content
        isReply
        isAuthor
        createdAt
        updatedAt
      }
      isAuthor
      event {
        id
        title
        description
        venue
        startAt
        endAt
        allDay
        isCancelled
        repeat
        until
        forever
        eventType
        isPublic
        cancelledDates
        bookmarksCount
        isBookmarked
        isAuthor
        commentsCount
        createdAt
        updatedAt
      }
      author {
        id
        name
        email
        pictureUrl
        followingCount
        createdCount
      }
      createdAt
      updatedAt
    }
    isAuthor
    event {
      id
      title
      description
      venue
      startAt
      endAt
      allDay
      isCancelled
      repeat
      until
      forever
      eventType
      schedule {
        id
        name
        description
        status
        isPublic
        isFollowing
        isAuthor
        eventsCount
        followersCount
        createdAt
        updatedAt
      }
      isPublic
      cancelledDates
      bookmarksCount
      isBookmarked
      isAuthor
      author {
        id
        name
        email
        pictureUrl
        followingCount
        createdCount
      }
      commentsCount
      comments {
        id
        content
        isReply
        isAuthor
        createdAt
        updatedAt
      }
      createdAt
      updatedAt
    }
    author {
      id
      name
      email
      pictureUrl
      followingCount
      createdCount
      createdSchedules {
        id
        name
        description
        status
        isPublic
        isFollowing
        isAuthor
        eventsCount
        followersCount
        createdAt
        updatedAt
      }
      followingSchedules {
        id
        name
        description
        status
        isPublic
        isFollowing
        isAuthor
        eventsCount
        followersCount
        createdAt
        updatedAt
      }
    }
    createdAt
    updatedAt
  }
}
`;
export const updateComment = `mutation UpdateComment($input: UpdateCommentInput!) {
  updateComment(input: $input) {
    id
    content
    isReply
    toComment {
      id
      content
      isReply
      toComment {
        id
        content
        isReply
        isAuthor
        createdAt
        updatedAt
      }
      isAuthor
      event {
        id
        title
        description
        venue
        startAt
        endAt
        allDay
        isCancelled
        repeat
        until
        forever
        eventType
        isPublic
        cancelledDates
        bookmarksCount
        isBookmarked
        isAuthor
        commentsCount
        createdAt
        updatedAt
      }
      author {
        id
        name
        email
        pictureUrl
        followingCount
        createdCount
      }
      createdAt
      updatedAt
    }
    isAuthor
    event {
      id
      title
      description
      venue
      startAt
      endAt
      allDay
      isCancelled
      repeat
      until
      forever
      eventType
      schedule {
        id
        name
        description
        status
        isPublic
        isFollowing
        isAuthor
        eventsCount
        followersCount
        createdAt
        updatedAt
      }
      isPublic
      cancelledDates
      bookmarksCount
      isBookmarked
      isAuthor
      author {
        id
        name
        email
        pictureUrl
        followingCount
        createdCount
      }
      commentsCount
      comments {
        id
        content
        isReply
        isAuthor
        createdAt
        updatedAt
      }
      createdAt
      updatedAt
    }
    author {
      id
      name
      email
      pictureUrl
      followingCount
      createdCount
      createdSchedules {
        id
        name
        description
        status
        isPublic
        isFollowing
        isAuthor
        eventsCount
        followersCount
        createdAt
        updatedAt
      }
      followingSchedules {
        id
        name
        description
        status
        isPublic
        isFollowing
        isAuthor
        eventsCount
        followersCount
        createdAt
        updatedAt
      }
    }
    createdAt
    updatedAt
  }
}
`;
export const deleteComment = `mutation DeleteComment($input: DeleteCommentInput!) {
  deleteComment(input: $input) {
    id
    content
    isReply
    toComment {
      id
      content
      isReply
      toComment {
        id
        content
        isReply
        isAuthor
        createdAt
        updatedAt
      }
      isAuthor
      event {
        id
        title
        description
        venue
        startAt
        endAt
        allDay
        isCancelled
        repeat
        until
        forever
        eventType
        isPublic
        cancelledDates
        bookmarksCount
        isBookmarked
        isAuthor
        commentsCount
        createdAt
        updatedAt
      }
      author {
        id
        name
        email
        pictureUrl
        followingCount
        createdCount
      }
      createdAt
      updatedAt
    }
    isAuthor
    event {
      id
      title
      description
      venue
      startAt
      endAt
      allDay
      isCancelled
      repeat
      until
      forever
      eventType
      schedule {
        id
        name
        description
        status
        isPublic
        isFollowing
        isAuthor
        eventsCount
        followersCount
        createdAt
        updatedAt
      }
      isPublic
      cancelledDates
      bookmarksCount
      isBookmarked
      isAuthor
      author {
        id
        name
        email
        pictureUrl
        followingCount
        createdCount
      }
      commentsCount
      comments {
        id
        content
        isReply
        isAuthor
        createdAt
        updatedAt
      }
      createdAt
      updatedAt
    }
    author {
      id
      name
      email
      pictureUrl
      followingCount
      createdCount
      createdSchedules {
        id
        name
        description
        status
        isPublic
        isFollowing
        isAuthor
        eventsCount
        followersCount
        createdAt
        updatedAt
      }
      followingSchedules {
        id
        name
        description
        status
        isPublic
        isFollowing
        isAuthor
        eventsCount
        followersCount
        createdAt
        updatedAt
      }
    }
    createdAt
    updatedAt
  }
}
`;
export const createEvent = `mutation CreateEvent($input: CreateEventInput!) {
  createEvent(input: $input) {
    id
    title
    description
    venue
    startAt
    endAt
    allDay
    isCancelled
    repeat
    until
    forever
    eventType
    schedule {
      id
      name
      description
      status
      isPublic
      isFollowing
      isAuthor
      author {
        id
        name
        email
        pictureUrl
        followingCount
        createdCount
      }
      eventsCount
      followersCount
      followers {
        id
        name
        email
        pictureUrl
        followingCount
        createdCount
      }
      events {
        id
        title
        description
        venue
        startAt
        endAt
        allDay
        isCancelled
        repeat
        until
        forever
        eventType
        isPublic
        cancelledDates
        bookmarksCount
        isBookmarked
        isAuthor
        commentsCount
        createdAt
        updatedAt
      }
      createdAt
      updatedAt
    }
    isPublic
    cancelledDates
    bookmarksCount
    isBookmarked
    isAuthor
    author {
      id
      name
      email
      pictureUrl
      followingCount
      createdCount
      createdSchedules {
        id
        name
        description
        status
        isPublic
        isFollowing
        isAuthor
        eventsCount
        followersCount
        createdAt
        updatedAt
      }
      followingSchedules {
        id
        name
        description
        status
        isPublic
        isFollowing
        isAuthor
        eventsCount
        followersCount
        createdAt
        updatedAt
      }
    }
    commentsCount
    comments {
      id
      content
      isReply
      toComment {
        id
        content
        isReply
        isAuthor
        createdAt
        updatedAt
      }
      isAuthor
      event {
        id
        title
        description
        venue
        startAt
        endAt
        allDay
        isCancelled
        repeat
        until
        forever
        eventType
        isPublic
        cancelledDates
        bookmarksCount
        isBookmarked
        isAuthor
        commentsCount
        createdAt
        updatedAt
      }
      author {
        id
        name
        email
        pictureUrl
        followingCount
        createdCount
      }
      createdAt
      updatedAt
    }
    createdAt
    updatedAt
  }
}
`;
export const updateEvent = `mutation UpdateEvent($input: UpdateEventInput!) {
  updateEvent(input: $input) {
    id
    title
    description
    venue
    startAt
    endAt
    allDay
    isCancelled
    repeat
    until
    forever
    eventType
    schedule {
      id
      name
      description
      status
      isPublic
      isFollowing
      isAuthor
      author {
        id
        name
        email
        pictureUrl
        followingCount
        createdCount
      }
      eventsCount
      followersCount
      followers {
        id
        name
        email
        pictureUrl
        followingCount
        createdCount
      }
      events {
        id
        title
        description
        venue
        startAt
        endAt
        allDay
        isCancelled
        repeat
        until
        forever
        eventType
        isPublic
        cancelledDates
        bookmarksCount
        isBookmarked
        isAuthor
        commentsCount
        createdAt
        updatedAt
      }
      createdAt
      updatedAt
    }
    isPublic
    cancelledDates
    bookmarksCount
    isBookmarked
    isAuthor
    author {
      id
      name
      email
      pictureUrl
      followingCount
      createdCount
      createdSchedules {
        id
        name
        description
        status
        isPublic
        isFollowing
        isAuthor
        eventsCount
        followersCount
        createdAt
        updatedAt
      }
      followingSchedules {
        id
        name
        description
        status
        isPublic
        isFollowing
        isAuthor
        eventsCount
        followersCount
        createdAt
        updatedAt
      }
    }
    commentsCount
    comments {
      id
      content
      isReply
      toComment {
        id
        content
        isReply
        isAuthor
        createdAt
        updatedAt
      }
      isAuthor
      event {
        id
        title
        description
        venue
        startAt
        endAt
        allDay
        isCancelled
        repeat
        until
        forever
        eventType
        isPublic
        cancelledDates
        bookmarksCount
        isBookmarked
        isAuthor
        commentsCount
        createdAt
        updatedAt
      }
      author {
        id
        name
        email
        pictureUrl
        followingCount
        createdCount
      }
      createdAt
      updatedAt
    }
    createdAt
    updatedAt
  }
}
`;
export const deleteEvent = `mutation DeleteEvent($input: DeleteEventInput!) {
  deleteEvent(input: $input) {
    id
    title
    description
    venue
    startAt
    endAt
    allDay
    isCancelled
    repeat
    until
    forever
    eventType
    schedule {
      id
      name
      description
      status
      isPublic
      isFollowing
      isAuthor
      author {
        id
        name
        email
        pictureUrl
        followingCount
        createdCount
      }
      eventsCount
      followersCount
      followers {
        id
        name
        email
        pictureUrl
        followingCount
        createdCount
      }
      events {
        id
        title
        description
        venue
        startAt
        endAt
        allDay
        isCancelled
        repeat
        until
        forever
        eventType
        isPublic
        cancelledDates
        bookmarksCount
        isBookmarked
        isAuthor
        commentsCount
        createdAt
        updatedAt
      }
      createdAt
      updatedAt
    }
    isPublic
    cancelledDates
    bookmarksCount
    isBookmarked
    isAuthor
    author {
      id
      name
      email
      pictureUrl
      followingCount
      createdCount
      createdSchedules {
        id
        name
        description
        status
        isPublic
        isFollowing
        isAuthor
        eventsCount
        followersCount
        createdAt
        updatedAt
      }
      followingSchedules {
        id
        name
        description
        status
        isPublic
        isFollowing
        isAuthor
        eventsCount
        followersCount
        createdAt
        updatedAt
      }
    }
    commentsCount
    comments {
      id
      content
      isReply
      toComment {
        id
        content
        isReply
        isAuthor
        createdAt
        updatedAt
      }
      isAuthor
      event {
        id
        title
        description
        venue
        startAt
        endAt
        allDay
        isCancelled
        repeat
        until
        forever
        eventType
        isPublic
        cancelledDates
        bookmarksCount
        isBookmarked
        isAuthor
        commentsCount
        createdAt
        updatedAt
      }
      author {
        id
        name
        email
        pictureUrl
        followingCount
        createdCount
      }
      createdAt
      updatedAt
    }
    createdAt
    updatedAt
  }
}
`;
export const createUser = `mutation CreateUser($input: CreateUserInput!) {
  createUser(input: $input) {
    id
    name
    email
    pictureUrl
    followingCount
    createdCount
    createdSchedules {
      id
      name
      description
      status
      isPublic
      isFollowing
      isAuthor
      author {
        id
        name
        email
        pictureUrl
        followingCount
        createdCount
      }
      eventsCount
      followersCount
      followers {
        id
        name
        email
        pictureUrl
        followingCount
        createdCount
      }
      events {
        id
        title
        description
        venue
        startAt
        endAt
        allDay
        isCancelled
        repeat
        until
        forever
        eventType
        isPublic
        cancelledDates
        bookmarksCount
        isBookmarked
        isAuthor
        commentsCount
        createdAt
        updatedAt
      }
      createdAt
      updatedAt
    }
    followingSchedules {
      id
      name
      description
      status
      isPublic
      isFollowing
      isAuthor
      author {
        id
        name
        email
        pictureUrl
        followingCount
        createdCount
      }
      eventsCount
      followersCount
      followers {
        id
        name
        email
        pictureUrl
        followingCount
        createdCount
      }
      events {
        id
        title
        description
        venue
        startAt
        endAt
        allDay
        isCancelled
        repeat
        until
        forever
        eventType
        isPublic
        cancelledDates
        bookmarksCount
        isBookmarked
        isAuthor
        commentsCount
        createdAt
        updatedAt
      }
      createdAt
      updatedAt
    }
  }
}
`;
export const updateUser = `mutation UpdateUser($input: UpdateUserInput!) {
  updateUser(input: $input) {
    id
    name
    email
    pictureUrl
    followingCount
    createdCount
    createdSchedules {
      id
      name
      description
      status
      isPublic
      isFollowing
      isAuthor
      author {
        id
        name
        email
        pictureUrl
        followingCount
        createdCount
      }
      eventsCount
      followersCount
      followers {
        id
        name
        email
        pictureUrl
        followingCount
        createdCount
      }
      events {
        id
        title
        description
        venue
        startAt
        endAt
        allDay
        isCancelled
        repeat
        until
        forever
        eventType
        isPublic
        cancelledDates
        bookmarksCount
        isBookmarked
        isAuthor
        commentsCount
        createdAt
        updatedAt
      }
      createdAt
      updatedAt
    }
    followingSchedules {
      id
      name
      description
      status
      isPublic
      isFollowing
      isAuthor
      author {
        id
        name
        email
        pictureUrl
        followingCount
        createdCount
      }
      eventsCount
      followersCount
      followers {
        id
        name
        email
        pictureUrl
        followingCount
        createdCount
      }
      events {
        id
        title
        description
        venue
        startAt
        endAt
        allDay
        isCancelled
        repeat
        until
        forever
        eventType
        isPublic
        cancelledDates
        bookmarksCount
        isBookmarked
        isAuthor
        commentsCount
        createdAt
        updatedAt
      }
      createdAt
      updatedAt
    }
  }
}
`;
export const deleteUser = `mutation DeleteUser($input: DeleteUserInput!) {
  deleteUser(input: $input) {
    id
    name
    email
    pictureUrl
    followingCount
    createdCount
    createdSchedules {
      id
      name
      description
      status
      isPublic
      isFollowing
      isAuthor
      author {
        id
        name
        email
        pictureUrl
        followingCount
        createdCount
      }
      eventsCount
      followersCount
      followers {
        id
        name
        email
        pictureUrl
        followingCount
        createdCount
      }
      events {
        id
        title
        description
        venue
        startAt
        endAt
        allDay
        isCancelled
        repeat
        until
        forever
        eventType
        isPublic
        cancelledDates
        bookmarksCount
        isBookmarked
        isAuthor
        commentsCount
        createdAt
        updatedAt
      }
      createdAt
      updatedAt
    }
    followingSchedules {
      id
      name
      description
      status
      isPublic
      isFollowing
      isAuthor
      author {
        id
        name
        email
        pictureUrl
        followingCount
        createdCount
      }
      eventsCount
      followersCount
      followers {
        id
        name
        email
        pictureUrl
        followingCount
        createdCount
      }
      events {
        id
        title
        description
        venue
        startAt
        endAt
        allDay
        isCancelled
        repeat
        until
        forever
        eventType
        isPublic
        cancelledDates
        bookmarksCount
        isBookmarked
        isAuthor
        commentsCount
        createdAt
        updatedAt
      }
      createdAt
      updatedAt
    }
  }
}
`;
